name: automct
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - tqdm
  - tifffile
  - pillow
  - pandas
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - opencv-python
    - plotly
    - kaleido